[package]
name = "chatmf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
src = "src/bin/server.rs"

[[bin]]
name = "client"
src = "src/bin/client.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "chatmf"
path = "src/lib.rs"
